### ISSUE TITLE
Problem executing the demo

### ISSUE THREAD

**Issue by aminabs** [marlonrichert/vaadin-material-design#2]
Hi there,
Thanks for your great design!
I've faced a runtime exception while trying to launch the demo application. The issue is that the server is looking for a file at some point inside the **demo project's webapp** directory whereas the file seems to be somewhere under the webapp directory of the addon project. The following shows the details about the exception. Thanks in advance for any later help:

`WARNING: Error persisting scss cache {MY-LOCAL-PROJECT-DIR}\vaadin-material-design\material-design-demo\src\main\webapp\VAADIN\themes\md-light\styles.scss.cache
java.io.FileNotFoundException: {MY-LOCAL-PROJECT-DIR}\vaadin-material-design\material-design-demo\src\main\webapp\VAADIN\themes\md-light\styles.scss.cache (The system cannot find the path specified)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at com.google.gwt.thirdparty.guava.common.io.Files$FileByteSink.openStream(Files.java:201)
    at com.google.gwt.thirdparty.guava.common.io.Files$FileByteSink.openStream(Files.java:189)
    at com.google.gwt.thirdparty.guava.common.io.ByteSink$AsCharSink.openStream(ByteSink.java:163)
    at com.google.gwt.thirdparty.guava.common.io.CharSink.write(CharSink.java:110)
    at com.google.gwt.thirdparty.guava.common.io.Files.write(Files.java:477)
    at com.vaadin.server.VaadinServlet.persistCacheEntry(VaadinServlet.java:1304)
    at com.vaadin.server.VaadinServlet.serveOnTheFlyCompiledScss(VaadinServlet.java:966)
    at com.vaadin.server.VaadinServlet.serveStaticResourcesInVAADIN(VaadinServlet.java:734)
    at com.vaadin.server.VaadinServlet.serveStaticResources(VaadinServlet.java:699)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:343)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
    at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by marlonrichert** [comment]
Sorry, I have no idea what that is about. (Also, I am not actively maintaining this project at the moment.)
